[tool.poetry]
name = "secateur"
version = "0.1.0"
description = ""
authors = ["Tom Eastman <tom@eastman.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.2"
social-auth-app-django = "^4.0.0"
python-twitter = "^3.5"
psycopg2-binary = "^2.8.6"
celery = {version = "^5.0.1", extras = ["redis,sqs"]}
redis = "^3.5.3"
django-redis = "^4.12.1"
gunicorn = "^20.0.4"
whitenoise = "^5.2.0"
django-bootstrap3 = "^14.2.0"
django-celery-beat = "^2.1.0"
dj-database-url = "^0.5.0"
django-csp = "^3.7"
django-request = "^1.5.6"
django-xff = "^1.3.0"
django-structlog = "^1.6.2"
django-bootstrap4 = "^2.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-django = "^4.1.0"
pytest-cov = "^2.10.1"
pytest-mypy = "^0.7.0"
pytest-black = "^0.3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
