# Generated by Django 2.0.4 on 2018-04-14 23:03

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(editable=False, max_length=30, null=True)),
                ('profile_updated', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'block'), (2, 'mute')])),
                ('until', models.DateTimeField()),
                ('activated', models.BooleanField(default=False, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secateur.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'follows'), (2, 'blocks'), (3, 'mutes')], editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('object', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_object_set', to='secateur.Account')),
                ('subject', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_subject_set', to='secateur.Account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cut',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secateur.User'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='secateur.Profile'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['type', 'subject'], name='secateur_re_type_2c4b68_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['type', 'object'], name='secateur_re_type_2db0bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('type', 'subject', 'object')},
        ),
        migrations.AlterUniqueTogether(
            name='cut',
            unique_together={('user', 'account', 'type')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['screen_name'], name='secateur_ac_screen__f4a619_idx'),
        ),
    ]
