# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 08:01
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('user_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(db_index=True, editable=False, max_length=30, null=True)),
                ('profile_updated', models.DateTimeField(editable=False, null=True)),
                ('followers_updated', models.DateTimeField(editable=False, null=True)),
                ('friends_updated', models.DateTimeField(editable=False, null=True)),
                ('blocks_updated', models.DateTimeField(editable=False, null=True)),
                ('mutes_updated', models.DateTimeField(editable=False, null=True)),
                ('blocks', models.ManyToManyField(editable=False, related_name='blocked_by', to='secateur.Twitter')),
                ('followers', models.ManyToManyField(editable=False, related_name='friends', to='secateur.Twitter')),
                ('mutes', models.ManyToManyField(editable=False, related_name='muted_by', to='secateur.Twitter')),
            ],
            options={
                'ordering': ['screen_name', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fullprofile',
            name='twitter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secateur.Twitter'),
        ),
    ]
