# Generated by Django 2.0 on 2017-12-10 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Mute'), (2, 'Block')])),
                ('until', models.DateTimeField()),
                ('twitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secateur.Twitter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secateur.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='snip',
            unique_together={('user', 'twitter')},
        ),
    ]
