# Generated by Django 2.1.2 on 2018-10-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
