# Generated by Django 2.1.7 on 2019-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("secateur", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(editable=False, max_length=60, null=True),
        )
    ]
