# Generated by Django 2.1.2 on 2018-11-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0002_relationship_until'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cut',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cut',
            name='account',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cut',
        ),
    ]
