# Generated by Django 2.0 on 2017-12-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0002_auto_20171210_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snip',
            unique_together={('user', 'twitter', 'type')},
        ),
    ]
