# Generated by Django 2.2 on 2019-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0003_auto_20190414_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
