# Generated by Django 2.0 on 2017-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0003_auto_20171210_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='until',
            field=models.DateTimeField(db_index=True),
        ),
    ]
