# Generated by Django 2.2 on 2019-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("secateur", "0004_auto_20190414_1505")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_twitter_api_enabled",
            field=models.BooleanField(default=False),
        )
    ]
