# Generated by Django 2.0 on 2017-12-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0005_auto_20171216_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='blocks',
        ),
    ]
