# Generated by Django 2.0 on 2017-12-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0006_remove_twitter_blocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='blocks2',
            new_name='blocks',
        ),
    ]
