# Generated by Django 2.2.4 on 2019-08-28 07:03

from django.db import migrations


def update_user_account(apps, schema_editor):
    UserSocialAuth = apps.get_model("social_django", "UserSocialAuth")
    Account = apps.get_model("secateur", "Account")
    for social_auth in UserSocialAuth.objects.all():
        if social_auth.provider != "twitter":
            continue
        user = social_auth.user
        uid = int(social_auth.uid)
        if user.account_id != uid:
            account, created = Account.objects.get_or_create(user_id=uid)
        user.account = account
        user.save(update_fields=("account",))


def user_account_null(apps, schema_editor):
    User = apps.get_model("secateur", "User")
    User.objects.update(account=None)


class Migration(migrations.Migration):

    dependencies = [
        ("social_django", "0008_partial_timestamp"),
        ("secateur", "0007_user_account"),
    ]

    operations = [
        migrations.RunPython(update_user_account, reverse_code=user_account_null)
    ]
