# Generated by Django 2.0 on 2017-12-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0007_auto_20171216_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor_page_number', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='followers',
        ),
        migrations.AlterField(
            model_name='twitter',
            name='blocks',
            field=models.ManyToManyField(related_name='blocked_by', through='secateur.Block', to='secateur.Twitter'),
        ),
        migrations.AddField(
            model_name='follow',
            name='from_twitter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='secateur.Twitter'),
        ),
        migrations.AddField(
            model_name='follow',
            name='to_twitter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='secateur.Twitter'),
        ),
    ]
