# Generated by Django 2.2.4 on 2020-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0008_populate_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_twitter_api_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
