# Generated by Django 2.0 on 2017-12-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0008_auto_20171216_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follower',
        ),
        migrations.AddField(
            model_name='twitter',
            name='followers',
            field=models.ManyToManyField(related_name='followed_by', through='secateur.Follower', to='secateur.Twitter'),
        ),
    ]
