# Generated by Django 2.0 on 2017-12-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0009_auto_20171216_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='mutes',
        ),
    ]
