# Generated by Django 3.0.6 on 2020-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0011_auto_20200530_1841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmessage",
            name="message",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
