# Generated by Django 2.0 on 2017-12-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0011_mute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor_page_number', models.IntegerField(blank=True, editable=False, null=True)),
                ('from_twitter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='secateur.Twitter')),
                ('to_twitter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='secateur.Twitter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='twitter',
            name='friends',
            field=models.ManyToManyField(related_name='friended_by', through='secateur.Friend', to='secateur.Twitter'),
        ),
    ]
