# Generated by Django 2.0 on 2017-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0012_auto_20171216_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='mutes',
            field=models.ManyToManyField(related_name='muted_by', through='secateur.Mute', to='secateur.Twitter'),
        ),
    ]
