# Generated by Django 3.0.7 on 2020-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0014_auto_20200608_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="favourites_count",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="followers_count",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="friends_count",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="listed_count",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="location",
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="profile_banner_url",
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="profile_image_url_https",
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="statuses_count",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
