# Generated by Django 3.0.7 on 2020-06-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0016_auto_20200610_1121"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="profile",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
