# Generated by Django 3.0.7 on 2020-06-11 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0018_auto_20200611_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmessage",
            name="account",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="secateur.Account",
            ),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="user",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="object",
            field=models.ForeignKey(
                db_index=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_object_set",
                to="secateur.Account",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="subject",
            field=models.ForeignKey(
                db_index=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_subject_set",
                to="secateur.Account",
            ),
        ),
    ]
