# Generated by Django 3.0.7 on 2020-06-11 10:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0020_auto_20200611_1645"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="relationship",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["until"], name="secateur_re_until_54d335_brin"
            ),
        ),
    ]
