# Generated by Django 3.0.7 on 2020-06-11 10:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0021_auto_20200611_2236"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="relationship",
            name="secateur_re_until_54d335_brin",
        ),
        migrations.AddIndex(
            model_name="account",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True,
                fields=["profile_updated"],
                name="secateur_ac_profile_34f54f_brin",
            ),
        ),
        migrations.AddIndex(
            model_name="logmessage",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["time"], name="secateur_lo_time_9f1798_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="logmessage",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True,
                fields=["action"],
                name="secateur_lo_action_60b44a_brin",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True,
                fields=["until"],
                name="secateur_re_until_54d335_brin",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True,
                fields=["updated"],
                name="secateur_re_updated_7487ee_brin",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["type"], name="secateur_re_type_e76852_brin"
            ),
        ),
    ]
