# Generated by Django 3.0.7 on 2020-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0022_auto_20200611_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='rate_limited',
            field=models.BooleanField(null=True),
        ),
    ]
