# Generated by Django 3.0.7 on 2020-06-14 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0023_logmessage_rate_limited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logmessage",
            name="message",
        ),
    ]
