# Generated by Django 3.0.7 on 2020-07-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0025_auto_20200626_1122"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="logmessage",
            name="secateur_lo_user_id_e2e246_idx",
        ),
        migrations.RemoveIndex(
            model_name="logmessage",
            name="secateur_lo_action_60b44a_brin",
        ),
        migrations.AddIndex(
            model_name="logmessage",
            index=models.Index(fields=["action"], name="secateur_lo_action_87c51f_idx"),
        ),
    ]
