# Generated by Django 3.0.7 on 2020-07-04 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0026_auto_20200704_1359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
