# Generated by Django 3.0.7 on 2020-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0028_auto_20200704_1409'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logmessage',
            name='secateur_lo_user_id_d17035_idx',
        ),
        migrations.AddIndex(
            model_name='logmessage',
            index=models.Index(fields=['user'], name='secateur_lo_user_id_51bdd0_idx'),
        ),
    ]
