# Generated by Django 3.0.8 on 2020-08-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0031_auto_20200704_1437"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="account",
            name="secateur_ac_screen__cf1d38_idx",
        ),
        migrations.RemoveField(
            model_name="account",
            name="screen_name_lower",
        ),
    ]
