# Generated by Django 3.1 on 2020-09-26 21:27

from django.db import migrations, models
import secateur.models


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0034_auto_20200903_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token_bucket_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="token_bucket_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="token_bucket_value",
            field=models.FloatField(default=secateur.models.default_token_bucket_max),
        ),
    ]
