# Generated by Django 3.1 on 2020-09-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secateur', '0035_auto_20200927_1027'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='relationship',
            name='until_brin',
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(until__isnull=False), fields=['until'], name='until_brin_btree'),
        ),
    ]
