# Generated by Django 4.0.4 on 2022-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0039_auto_20210314_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oauth_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_token_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
