# Generated by Django 4.0.4 on 2022-04-20 22:06

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0040_user_oauth_token_user_oauth_token_secret"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="logmessage",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="relationship",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="oauth_token",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="oauth_token_secret",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
