# Generated by Django 4.0.4 on 2022-04-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0041_alter_account_managers_alter_logmessage_managers_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="logmessage",
            name="secateur_lo_time_9f1798_brin",
        ),
        migrations.AddIndex(
            model_name="logmessage",
            index=models.Index(
                fields=["user", "-id"], name="secateur_lo_user_id_e74853_idx"
            ),
        ),
    ]
