# Generated by Django 4.0.4 on 2022-04-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0042_remove_logmessage_secateur_lo_time_9f1798_brin_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="logmessage",
            name="secateur_lo_user_id_a8697e_idx",
        ),
        migrations.RemoveIndex(
            model_name="logmessage",
            name="secateur_lo_user_id_e74853_idx",
        ),
        migrations.AddIndex(
            model_name="logmessage",
            index=models.Index(
                fields=["user", "-id", "action"], name="log_user_id_action"
            ),
        ),
    ]
