# Generated by Django 4.0.4 on 2022-04-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0044_remove_logmessage_log_user_id_action_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="relationship",
            name="secateur_re_type_2db0bf_idx",
        ),
        migrations.RemoveIndex(
            model_name="relationship",
            name="secateur_re_updated_7487ee_brin",
        ),
    ]
