# Generated by Django 4.0.4 on 2022-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secateur", "0045_remove_relationship_secateur_re_type_2db0bf_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="description",
            field=models.CharField(editable=False, max_length=250, null=True),
        ),
    ]
