# Generated by Django 4.0.7 on 2022-08-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0048_remove_relationship_until_btree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_until",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
