# Generated by Django 4.0.9 on 2023-03-30 00:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secateur", "0049_user_max_until"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="logmessage",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["time"], name="secateur_lo_time_9f1798_brin"
            ),
        ),
    ]
