#!/bin/bash

set -eux

FILE_LIST=$(mktemp)
SCALE_BLOCKER=1

cd $(dirname $0)/..
git ls-files > ${FILE_LIST}
rsync -av --files-from=${FILE_LIST} . ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}

ssh -t ${DEPLOY_USER}@${DEPLOY_HOST} "
   cd ${DEPLOY_DIRECTORY}
   sudo docker-compose -f docker-compose-live.yml stop celery blocker
   sudo docker-compose -f docker-compose-live.yml build --pull
   sudo docker-compose -f docker-compose-live.yml up --detach --scale blocker=${SCALE_BLOCKER}
"
