#!/bin/bash

set -eux

FILE_LIST=$(mktemp)

cd $(dirname $0)/..
git ls-files > ${FILE_LIST}
rsync -av --files-from=${FILE_LIST} . ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}

ssh ${DEPLOY_USER}@${DEPLOY_HOST} "
   cd ${DEPLOY_DIRECTORY}
   ${DEPLOY_PIPENV} run ./manage.py migrate
   ${DEPLOY_PIPENV} run ./manage.py collectstatic --noinput
   systemctl --user restart secateur
"
