name: Build Secateur
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install poetry
      - run: poetry install
      - run: poetry run black --check .

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest
        env:
          DATABASE_URL: postgres://postgres@localhost/postgres
